# What is Numpy

NumPy is a Python library that provides support for large, multi-dimensional arrays and high-performance mathematical functions for numerical computing.

NumPy provides a special data structure called an ndarray (N-dimensional Array) that allows us to store and process large amounts of numerical data efficiently.

NumPy stands for Numerical Python. It is an open-source Python library used for:

Numerical computations<br>
Mathematical operations<br>
Working with arrays and matrices<br>
Scientific computing<br>
Data Analysis<br>
Machine Learning<br>

## Why NumPy is Needed

Python is an excellent programming language, but it was not originally designed for heavy numerical computations.

When dealing with:

-- Millions of records<br>
-- Mathematical calculations<br>
-- Statistical analysis<br>
-- Machine Learning datasets<br>

Python Lists become slow and memory-intensive. To solve these problems, NumPy was developed.

#### Example

Suppose a company has sales data for 5 million transactions.

Tasks:

-- Calculate total sales<br>
-- Find average sales<br>
-- Identify highest and lowest sales<br>

###### Using Python Lists:

-- More memory usage<br>
-- Slower calculations<br>

###### Using NumPy:

-- Less memory usage<br>
-- Faster calculations<br>
-- Optimized performance

#### Creating a Python List

In [5]:
import sys
num = [45,46,89,67]
print(sys.getsizeof(num))
num.remove(67)
print(sys.getsizeof(num))

56


In [9]:
import numpy as np
arr = np.array([45,46,89,67])
print(arr.itemsize)
print(arr.nbytes)

8
32


In [3]:
num1 = [34,45,46,47]
num2 = [34,45,46,47]
print(num1+num2)
print(sum(num1))

[34, 45, 46, 47, 34, 45, 46, 47]
172


In [4]:
array1 = np.array([34,45,46,47])
array2 = np.array([34,45,46,47])
print(array1+array2)
print(sum(array1))

[68 90 92 94]
172


## Numpy Array Creations

In [5]:
import numpy as np

In [6]:
# 0 Dimenstion Array
arr1 = np.array(45)
print(arr1)
print(type(arr1))
print("No of Dimentions:",arr1.ndim)
print(arr1.shape)

45
<class 'numpy.ndarray'>
No of Dimentions: 0
()


In [7]:
# 1 Dimenstion Array
arr1 = np.array([45,67,89,90])
print(arr1)
print(type(arr1))
print("No of Dimentions:",arr1.ndim)
print(arr1.shape)
print("Number of Rows:",arr1.shape[0])
# print("Number of Columns:",arr1.shape[1])

[45 67 89 90]
<class 'numpy.ndarray'>
No of Dimentions: 1
(4,)
Number of Rows: 4


In [8]:
# 2 Dimenstional Array
arr1 = np.array([[45,67,89,90],[76,34,90,31]])
print(arr1)
print(type(arr1))
print("No of Dimentions:",arr1.ndim)
print(arr1.shape)
print("Number of Rows:",arr1.shape[0])
print("Number of Columns:",arr1.shape[1])

[[45 67 89 90]
 [76 34 90 31]]
<class 'numpy.ndarray'>
No of Dimentions: 2
(2, 4)
Number of Rows: 2
Number of Columns: 4


In [9]:
# 3 Dimenstional Array
arr1 = np.array([[[45,67,89,90],[76,34,90,31]],[[45,67,89,90],[76,34,90,31]]])
print(arr1)
print(type(arr1))
print("No of Dimentions:",arr1.ndim)
print(arr1.shape)


[[[45 67 89 90]
  [76 34 90 31]]

 [[45 67 89 90]
  [76 34 90 31]]]
<class 'numpy.ndarray'>
No of Dimentions: 3
(2, 2, 4)


## Array Indexing & Slicing

In [10]:
list1 = [78,34,89,38]
print(list1[0])
print(list1[1:2])
print(list1[1:3])

78
[34]
[34, 89]


In [11]:
array1 = np.array([78,34,89,38])
# print(array1[0])
# print(array1[1:2])
# print(array1[1:3])
print(array1[:])
print(array1[1:])
print(array1[:2])
print(array1[:100])
print(array1[100:200])
print(array1[::-1])
print(np.sort(array1)[::-1])
print(np.sort(array1))

[78 34 89 38]
[34 89 38]
[78 34]
[78 34 89 38]
[]
[38 89 34 78]
[89 78 38 34]
[34 38 78 89]


In [12]:
## 2D Array Indexing & Slicing
array2=np.array([
    [11,12,13,14,15,16],
    [61,51,41,31,21,11],
    [12,23,34,45,56,67],
    [76,65,54,43,21,10]
])
# print(array2)
# print(array2.ndim)
# print(array2.shape)
## Indexing
# print(array2[1,2])
# array2[1][0]=100
# print(array2)
# print(array2[0:1,:])
# print(array2[:,0:1])
# print(array2[1:3,1:5])
# print(array2[2:4,4:6])
# array2[2:4,4:6] = 0

# x = np.array([[23,34],[45,56]])
# array2[2:4,4:6] = x
# print(array2)

## Copy & View

In [ ]:
num1 = np.array([12,13,14,15])
x = num1.copy()
print(num1)
print(x)
num1[0] = 100
print(num1)
print(x)

In [ ]:
num1 = np.array([12,13,14,15])
x = num1.view()
print(num1)
print(x)
num1[0] = 100
print(num1)
print(x)

## Shape & Reshape

In [ ]:
array1 = np.array([1, 2, 3, 4, 5,  6,  7,  8,  9, 10, 11, 12])
print(array1)
print(array1.ndim)
print(array1.shape)

In [ ]:
x = array1.reshape(3,4)
print(x)
print(x.ndim)
print(x.shape)

In [ ]:
y = array1.reshape(2,2,3)
print(y)
print(y.ndim)
print(y.shape)

## Array Iteration

In [ ]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(len(a1))
for i in a1:
    print(i, end=" ")

In [ ]:
a2 = a1.reshape(3,4)
print(len(a2))
for i in a2:
    for j in i:
        print(j,end=" ")

In [ ]:
a3 = a1.reshape(2,2,3)
print(a3)
for i in a3:
    for j in i:
        for k in j:
            print(k, end=" ")

In [ ]:
for i in np.nditer(a3):
    print(i,end=" ")

## Searching & Sorting

In [1]:
import numpy as np

In [3]:
arr1 = np.array([78,21,65,43,90])
x = np.sort(arr1)
print(x)

[21 43 65 78 90]


In [4]:
arr1 = np.array([78,21,65,43,90])
x = np.sort(arr1)[::-1]
print(x)

[90 78 65 43 21]


In [8]:
num1 = [78,21,65,43,21,21,43,21,78]
# print(num1.index(21))
for i in range(len(num1)):
    if num1[i] == 21:
        print(i)

1
4
5
7


In [10]:
arr2 = np.array([78,21,65,43,21,21,43,21,78])
x = np.where(arr2==21)
print(x)
print(type(x))

(array([1, 4, 5, 7]),)
<class 'tuple'>


In [13]:
arr3 = np.array([23,45,32,68])
value = [False,False,True,True]
arr3 = arr3[value]
print(arr3)

[32 68]


In [1]:
import numpy as np
arr4 = np.array([23,25,67,34,46,68])
value = []
for i in arr4:
    if i%2==0:
        value.append(True)
    else:
        value.append(False)
print(value)
arr4 = arr4[value]
print(arr4)
print(type(arr4))

[False, False, False, True, True, True]
[34 46 68]
<class 'numpy.ndarray'>


## Numpy Functions

In [19]:
result = []
for i in range(1,11):
    result.append(i)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [22]:
x = np.arange(1,13)
print(x)
print(x.ndim)
result = x.reshape(3,4)
print(result)
print(result.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [24]:
x = np.zeros(12,'I')
print(x)
print(x.ndim)
result = x.reshape(3,4)
print(result)
print(result.ndim)

[0 0 0 0 0 0 0 0 0 0 0 0]
1
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
2


In [25]:
x = np.ones(12,'I')
print(x)
print(x.ndim)
result = x.reshape(3,4)
print(result)
print(result.ndim)

[1 1 1 1 1 1 1 1 1 1 1 1]
1
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
2


In [26]:
x = np.linspace(0,10,5)
print(x)

[ 0.   2.5  5.   7.5 10. ]
