In [1]:
import numpy as np

In [14]:
arr1 = np.array([[4,6],[8,10]])
arr2 = np.array([[2,4],[6,8]])

In [15]:
print(arr1)
print(arr2)

[[ 4  6]
 [ 8 10]]
[[2 4]
 [6 8]]


In [16]:
print(arr1 + arr2)

[[ 6 10]
 [14 18]]


In [17]:
print(arr1 - arr2)

[[2 2]
 [2 2]]


In [18]:
print(arr1 * arr2)

[[ 8 24]
 [48 80]]


In [19]:
print(arr1 / arr2)

[[2.         1.5       ]
 [1.33333333 1.25      ]]


In [20]:
print(arr1 @ arr2)

[[ 44  64]
 [ 76 112]]
