In [1]:
import numpy as np

In [6]:
for i in range(3,50,5):
    print(i)

3
8
13
18
23
28
33
38
43
48


## np.arange()

In [10]:
arr = np.arange(1,11,2)
print(arr)
print(arr.ndim)

[1 3 5 7 9]
1


In [16]:
arr = np.arange(1,10)
print(arr)
print(arr.shape)
print(arr.reshape(3,3))
arr = arr.reshape(3,3)
print(arr.ndim)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


## np.ones()

In [37]:
arr = np.ones(16,'I')
arr = arr.reshape(4,4)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint32)

## np.zeros()

In [58]:
arr = np.zeros(16,'I')
arr = arr.reshape(4,4)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint32)

## Problem 1

Replace 6,7,10,11 from 0

In [3]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr

array([[ 6,  7],
       [10, 11]])

In [42]:
arr[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

In [48]:
x = np.zeros(4)
newarr = x.reshape(2,2)
newarr

array([[0., 0.],
       [0., 0.]])

In [49]:
arr[1:3,1:3] = newarr
arr

array([[ 1,  2,  3,  4],
       [ 5,  0,  0,  8],
       [ 9,  0,  0, 12],
       [13, 14, 15, 16]])

## Problem No 2

I have 4,4 matrix and i want to replace 1st and 2nd element of 2nd and 3rd row with 0

In [57]:
one = np.ones(16)
one.reshape(4,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.linspace()

In [66]:
arr = np.linspace(1, 50, 5)
arr

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

## np.tranpose()

In [82]:
arr = np.array([[1, 2], [3, 4]])
print(arr)

newarr = np.transpose(arr)
print(newarr)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


## np.identity()

In [3]:
arr = np.identity(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## np.random

In [11]:
arr1 = np.random.randint(11,20,5)
print(arr1)

[13 18 12 13 18]


In [12]:
arr2 = np.random.rand(4)
print(arr2)

[0.84847448 0.92672101 0.57412719 0.19329518]


In [13]:
arr3 = np.random.randn(4)
print(arr3)

[-0.63567535 -0.45172762  0.09902291 -0.37057053]
