In [ ]:
import sys
num1 = [45,67,89,67]
print(sys.getsizeof(num1))
num1.remove(89)
print(sys.getsizeof(num1))

In [ ]:
import numpy as np
arr1 = np.array([45,67,89,67,89])
print(arr1.itemsize)
print(arr1.nbytes)

#### List vs Array Operations

In [ ]:
num1 = [23,34,45,69]
num2 = [23,34,45,69]
print(num1+num2)

In [ ]:
arr1 = np.array([23,34,45,69])
arr2 = np.array([23,34,45,69])
print(arr1+arr2)

In [ ]:
arr1 = np.array([23,34,45,69])
arr2 = np.array([23,34,45,69])
print(arr1-arr2)

In [ ]:
arr1 = np.array([23,34,45,69])
arr2 = np.array([23,34,45,69])
print(arr1*arr2)

In [ ]:
arr1 = np.array([23,34,45,69])
arr2 = np.array([23,34,45,69])
print(arr1/arr2)

#### Array Dimentions

In [ ]:
## 0 Dimentional Array
import numpy as np
arr1 = np.array(50)
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

In [ ]:
## 1 Dimentional Array
import numpy as np
arr1 = np.array([50,89,56,45])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

In [ ]:
## 2 Dimentional Array
import numpy as np
arr1 = np.array([[50,89],[56,45],[56,45]])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

In [ ]:
## 3 Dimentional Array
import numpy as np
arr1 = np.array([[[50,89],[56,45]],[[50,89],[56,45]]])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)

In [ ]:
import numpy as np
arr1 = np.array([[12,18],[16,20]])
arr2 = np.array([[2,3],[4,5]])
print(arr1)
print(arr2)
print(arr1*arr2)

In [1]:
import numpy as np
arr1 = np.array([[12,18],[16,20]])
arr2 = np.array([[2,3],[4,5]])
print(arr1@arr2)

[[ 96 126]
 [112 148]]


#### Array Indexing & Slicing

In [6]:
arr1 = np.array([23,34,45,23,67,78,23,81])
print(arr1[0])
print(np.where(arr1==23))

23
(array([0, 3, 6]),)


In [13]:
arr2 = np.array([[23,34,45,23],[67,78,23,81],[34,56,78,90]])
# print(arr2[0])
# print(arr2[1,2])
# # print(np.where(arr2==23))
print(arr2[1:3,2:4])

[[23 81]
 [78 90]]


In [18]:
arr3 = np.array([[[23,34,45],[67,78,81]],[[34,56,78],[44,60,80]]])
print(arr3.shape)
print(arr3.ndim)
print(arr3)

(2, 2, 3)
3
[[[23 34 45]
  [67 78 81]]

 [[34 56 78]
  [44 60 80]]]
